Removed direct env file dependency.

diff --git a/install b/install
--- a/install
+++ b/install
@@ -96,21 +96,30 @@ build_config() {
 }
 
 drpc-start() {
-    if [ -f "$DRPC_DIR/docker-compose.yml" ]; then
-        build_config ${CONFIG_PATH:-${DRPC_DIR}}
+    [ -z "$DRPC_DIR/.env.user" ] && { echo "Error: no .env.user found"; return 1; }
+    source "$DRPC_DIR/.env.user"
 
-        COMPOSE_FILE=$DRPC_DIR/docker-compose.yml docker compose --env-file $DRPC_DIR/.env.user pull
-        COMPOSE_FILE=$DRPC_DIR/docker-compose.yml docker compose --env-file $DRPC_DIR/.env.user up -d --remove-orphans --build
+    [ -f "$DRPC_DIR/docker-compose.yml" ] || { echo "DRPC proxy configuration file not found."; return 1; }
 
-        if [ ! -z "$DOCKER_NETWORKS" ]; then
-            nets=$(docker container inspect --format '{{range $net,$v := .NetworkSettings.Networks}}{{printf "%s\n" $net}}{{end}}' drpc-proxy)
-            for NETWORK in ${DOCKER_NETWORKS[@]}; do
-                [[ ! ${nets[@]} =~ "$NETWORK" ]] && docker network connect $NETWORK drpc-proxy
-            done
-        fi
-    else
-        echo "DRPC proxy configuration file not found."
-        return 1
+    build_config ${CONFIG_PATH:-${DRPC_DIR}}
+
+    DSHACKLE_TAG=$DSHACKLE_TAG \
+    COMPOSE_FILE=$DRPC_DIR/docker-compose.yml \
+    docker compose pull
+
+    DSHACKLE_TAG=$DSHACKLE_TAG \
+    PROVIDER=$PROVIDER \
+    HOST=$HOST \
+    CONFIG_PATH=$CONFIG_PATH \
+    KEYS_PATH=$KEYS_PATH \
+    COMPOSE_FILE=$DRPC_DIR/docker-compose.yml \
+    docker compose --env-file up -d --remove-orphans --build
+
+    if [ ! -z "$DOCKER_NETWORKS" ]; then
+        nets=$(docker container inspect --format '{{range $net,$v := .NetworkSettings.Networks}}{{printf "%s\n" $net}}{{end}}' drpc-proxy)
+        for NETWORK in ${DOCKER_NETWORKS[@]}; do
+            [[ ! ${nets[@]} =~ "$NETWORK" ]] && docker network connect $NETWORK drpc-proxy
+        done
     fi
 }
 
