Fixed volumes conflict.

diff --git a/install b/install
--- a/install
+++ b/install
@@ -55,15 +55,14 @@ reverseproxy-check() {
 }
 
 build_config() {
-    set -euo pipefail
-
-    [ -z $1 ] && { echo "Error: select destination path for config file"; return; }
+    # set -euo pipefail
+    [ -z $1 ] && { echo "Error: select destination path for config file"; return 1; }
     [ -f "$DRPC_DIR/.env.user" ] || { echo "Error: .env.user file not found"; return 1; }
     source $DRPC_DIR/.env.user
 
     INPUT="$DRPC_DIR/configs/dshackle.yaml"
     [ -f "$INPUT" ] || { echo "ERROR: $INPUT does not exist" >&2; return 1; }
-    OUTPUT="${1}/dshackle.yaml"
+    OUTPUT="${1}/${PROVIDER}-dshackle.yaml"
 
     export PROVIDER=$PROVIDER HOST=$HOST
     envsubst < "$INPUT" > "$OUTPUT"
@@ -77,7 +76,7 @@ build_config() {
     for i in "${!CHAINS[@]}"; do
         export ID=${IDS[i]} RPC=${RPCS[i]} WS=${WSS[i]}
 
-        CHAIN="${CHAINS[i]}.yaml"
+        CHAIN="$DRPC_DIR/configs/${CHAINS[i]}.yaml"
         if [[ ! -f "$CHAIN" ]]; then
             echo "WARNING: $CHAIN not found, skipping" >&2
             continue
@@ -98,8 +97,7 @@ build_config() {
 
 drpc-start() {
     if [ -f "$DRPC_DIR/docker-compose.yml" ]; then
-        [ -z $CONFIG_PATH ] && ! volume-exists drpc_config && docker volume create drpc_config
-        build_config ${CONFIG_PATH:-"/var/lib/docker/volumes/drpc_config/_data/"}
+        build_config ${CONFIG_PATH:-${DRPC_DIR}}
 
         [ -z $KEYS_PATH ] && ! volume-exists drpc_keys && docker volume create drpc_keys
         cp $DRPC_DIR/keys/* ${KEYS_PATH:-"/var/lib/docker/volumes/drpc_keys/_data/"}
